#ifndef MINIARCADEMACHINE_EXAMPLE_TILES_H
#define MINIARCADEMACHINE_EXAMPLE_TILES_H

#include <Arduino.h>

namespace Assets {
constexpr int16_t TILE_W = 16;
constexpr int16_t TILE_H = 16;

constexpr uint16_t SKY_BLUE = 0x7DFF;
constexpr uint16_t GROUND_LIGHT = 0xC3A6;
constexpr uint16_t GROUND_DARK = 0x8A22;

// Example 16x16 RGB565 tile. Draw with:
// display.pushImage(x, y, Assets::TILE_W, Assets::TILE_H, Assets::GROUND_TILE);
static const uint16_t GROUND_TILE[TILE_W * TILE_H] PROGMEM = {
    GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,  GROUND_LIGHT, GROUND_LIGHT, GROUND_LIGHT, GROUND_DARK,
    GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK,  GROUND_DARK
};
}

#endif // MINIARCADEMACHINE_EXAMPLE_TILES_H
